# Verificando versão

In [ ]:
!python --version

Python 3.7.12


# Numpy

In [ ]:
import numpy as np

In [ ]:
km = np.loadtxt('carros-km.txt')
km
anos = np.loadtxt('carros-anos.txt', dtype=int)
anos

### Obtendo a quilometragem média por ano

In [ ]:
km_media = km / (2021 - anos)
km_media

# Variáveis 

### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [ ]:
ano_atual = 2021
ano_fabricacao = 2013
km_total = 44410.0

In [ ]:
ano_atual

2021

In [ ]:
ano_fabricacao

2013

In [ ]:
km_total

44410.0

# $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

### Operações com variáveis

In [ ]:
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

5551.25

### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

In [ ]:
ano_atual, ano_fabricacao, km_total = 2021, 2013, 44410.0

In [ ]:
ano_atual

2021

In [ ]:
ano_fabricacao

2013

In [ ]:
km_total

44410.0

### Conversões de tipo

Funções int(), float(), str()

In [ ]:
int(103.3)

103

In [ ]:
float(10)

10.0

In [ ]:
float("10.1")

10.1

In [ ]:
str(10000)

'10000'

# Operações com listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Retorna **True** se um elemento da lista *A* for igual a *x*.

In [ ]:
lista = ["A", "B", "C", "D"]

In [ ]:
'A' in lista

True

In [ ]:
'A' not in lista

False

## *A + B*

Concatena as listas *A* e *B*.

In [ ]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [ ]:
C = A+B
C

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## *len(A)*

Tamanho da lista A.

In [ ]:
len(C)

8

# Seleções em listas

## *A[ i ]*

Retorna o i-ésimo item da lista *A*.

<font color=red>**Observação:**</font> Listas têm indexação com origem no zero.

In [ ]:
C[0]

'Rodas de liga'

In [ ]:
C[-1]

'Sensor de chuva'

In [ ]:
C[2]

'Piloto automático'

## *A[ i : j ]*

Recorta a lista *A* do índice i até o j. Neste fatiamento o elemento com índice i é **incluído** e o elemento com índice j **não é incluído** no resultado.

In [ ]:
C[:3]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [ ]:
C[1:]

['Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
C[2:3]

['Piloto automático']

In [ ]:
C[3:-1]

['Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular']

# Métodos de listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena a lista *A*.

In [ ]:
C.sort()
C

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.append(x)*

Adiciona o elemnto *x* no final da lista *A*.

In [ ]:
C.append('4 X 4')
C

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

## *A.pop(i)*

Remove e retorna o elemento de índice i da lista *A*.

<font color=red>**Observação:**</font> Por *default* o método *pop()* remove e retorna o último elemento de uma lista.

In [ ]:
C.pop()
C

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [ ]:
C.pop(2)

'Piloto automático'

In [ ]:
C

['Ar condicionado',
 'Bancos de couro',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.copy()*

Cria uma cópia da lista *A*.

<font color=red>**Observação:**</font> O mesmo resultado pode ser obtido com o seguinte código: 
```
A[:]
```

In [ ]:
D = C[:]
D

['Ar condicionado',
 'Bancos de couro',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [ ]:
E = D.copy()
E

['Ar condicionado',
 'Bancos de couro',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

# Instrução *for*

#### Formato padrão

```
for <variável> in <coleção>:
    <instruções>
```

### Loops com listas

In [ ]:
lista = ["A", "B", "C", "D", "E", "F", "G"]

In [ ]:
for item in lista:
  print(item)

A
B
C
D
E
F
G


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [ ]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
[i * 2 for i in range(10)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

# Loops aninhados

In [ ]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [ ]:
for lista in dados:
  for item in lista:
    print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [ ]:
acessorios = []

for lista in dados:
  for item in lista:
    acessorios.append(item)

acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [ ]:
list(set(acessorios))

['Controle de estabilidade',
 'Ar condicionado',
 'Rodas de liga',
 'Câmera de estacionamento',
 'Bancos de couro',
 'Vidros elétricos',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Câmbio automático',
 'Teto panorâmico',
 'Travas elétricas',
 'Sensor crepuscular',
 'Freios ABS',
 'Central multimídia',
 '4 X 4',
 'Painel digital',
 'Piloto automático']

### List comprehensions

In [ ]:
[item for lista in dados for item in lista]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

In [ ]:
list(set([item for lista in dados for item in lista]))

['Controle de estabilidade',
 'Ar condicionado',
 'Rodas de liga',
 'Câmera de estacionamento',
 'Bancos de couro',
 'Vidros elétricos',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Câmbio automático',
 'Teto panorâmico',
 'Travas elétricas',
 'Sensor crepuscular',
 'Freios ABS',
 'Central multimídia',
 '4 X 4',
 'Painel digital',
 'Piloto automático']

# Instrução *if*

#### Formato padrão

```
if <condição>:
     <instruções caso a condição seja verdadeira>
```

### Operadores de comparação: $==$, $!=$, $>$, $<$, $>=$, $<=$
### e
### Operadores lógicos: $and$, $or$, $not$

In [ ]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
for lista in dados:
  if lista[2]:
    print(lista)

['DS5', 2019, True]
['A5', 2019, True]


### List comprehensions

In [ ]:
[lista for lista in dados if lista[2]]

[['DS5', 2019, True], ['A5', 2019, True]]

# Criando arrays Numpy

In [ ]:
import numpy

In [ ]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [ ]:
import numpy as np

In [ ]:
teste = np.array([234, 2455, 289])

In [ ]:
type(teste)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [ ]:
teste.dtype

dtype('int64')

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [ ]:
km = np.loadtxt(fname = 'carros-km.txt', dtype=float)

In [ ]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [ ]:
km.dtype

dtype('float64')

### Arrays com duas dimensões

In [ ]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [ ]:
acessorios = np.array(dados)

In [ ]:
km.shape

(258,)

In [ ]:
acessorios.shape

(3, 8)

### Comparando desempenho com listas

In [ ]:
np_array = np.arange(1000000)

array([      2,       3,       4, ...,  999999, 1000000, 1000001])

In [ ]:
py_list = list(range(1000000))

In [ ]:
%time for _ in range(100): np_array *= 2

CPU times: user 61.8 ms, sys: 0 ns, total: 61.8 ms
Wall time: 63.6 ms


In [ ]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 9.55 s, sys: 2.34 s, total: 11.9 s
Wall time: 11.9 s


# Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [ ]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
# em lista isso não funciona
# idade = 2022 - anos

In [ ]:
import numpy as np
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [ ]:
idade = 2022 - anos

In [ ]:
idade

array([19, 31, 32,  3, 16])

### Operações entre arrays

In [ ]:
km_media = km / idade

In [ ]:
km_media

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

### Operações com arrays de duas dimensões

In [ ]:
dados = np.array([km, anos])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
dados[0][1]

5712.0

In [ ]:
km_media = dados[0] / (2022) - dados[1]

# Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
dados

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [ ]:
import numpy as np
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador[0]

0

In [ ]:
contador[-1]

9

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

In [ ]:
dados[0][1]

In [ ]:
dados[1][2]

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
contador[1:3]

array([1, 2])

In [ ]:
contador[1:8:2]

array([1, 3, 5, 7])

In [ ]:
contador[1:8:3]

array([1, 4, 7])

In [ ]:
contador[::2]

array([0, 2, 4, 6, 8])

In [ ]:
dados[:, 1:3][0]

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [ ]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
contador[contador < 5]

array([0, 1, 2, 3, 4])

# Atributos e métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [ ]:
dados = np.array([[12334, 232323, 44564, 45546, 64545],
                 [10, 122, 2121, 2121, 2123]])
dados

array([[ 12334, 232323,  44564,  45546,  64545],
       [    10,    122,   2121,   2121,   2123]])

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

In [ ]:
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [ ]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [ ]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [ ]:
dados.dtype

dtype('int64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [ ]:
dados.T

array([[ 12334,     10],
       [232323,    122],
       [ 44564,   2121],
       [ 45546,   2121],
       [ 64545,   2123]])

In [ ]:
dados.transpose()

array([[ 12334,     10],
       [232323,    122],
       [ 44564,   2121],
       [ 45546,   2121],
       [ 64545,   2123]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [ ]:
dados.tolist()

[[12334, 232323, 44564, 45546, 64545], [10, 122, 2121, 2121, 2123]]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
contador.reshape(5, 2, order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
contador.reshape(5, 2, order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [ ]:
np.array(info_carros).reshape(2, 5)

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [ ]:
np.array(info_carros).reshape(5, 2, order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [ ]:
dados_new = dados.copy()
dados_new

array([[ 12334, 232323,  44564,  45546,  64545],
       [    10,    122,   2121,   2121,   2123]])

In [ ]:
dados_new.resize(3, 5, refcheck=False)
dados_new

array([[ 12334, 232323,  44564,  45546,  64545],
       [    10,    122,   2121,   2121,   2123],
       [     0,      0,      0,      0,      0]])

In [ ]:
dados_new[2] = dados_new[0] / (2021 - dados_new[1])
dados_new

array([[ 12334, 232323,  44564,  45546,  64545],
       [    10,    122,   2121,   2121,   2123],
       [     6,    122,   -445,   -455,   -632]])

# Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [ ]:
import numpy as np
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [ ]:
anos.shape

(258,)

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [ ]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [ ]:
dataset.shape

(258, 3)

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [ ]:
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset[:, 2])

98960.51310077519

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [ ]:
np.std(dataset[:, 2])

29754.101150388564

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [ ]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [ ]:
dataset[:, 0].sum()

517938.0

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [ ]:
np.sum(dataset, axis =0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [ ]:
np.sum(dataset[:,1])

11480849.0